travis:
  secure:
    BINSTAR_TOKEN: kb11WoDvmhIs2GevA4VC+xO6p5qxMPemyoj20ZOqD7J7UokB8/2TB3mxnylSDS79FXefq/7KLmjZo7SvOmsAP2VsEEGkCK1f9xmXtYs9d+1PqXJ73ADwYl7QaDzarYgWe/BcZkhut79z4hyM6GT/J3ENYmzPUfJj+p7X6JL2ygQLvBfAD8Kx2Ibl00R0NeOTil0WgAhz2HE2LxaZHmLPRY5YjGZCIXhy3jxO8TFpOHeZOsBwtMf+K2+HMbNZdMm6gJAbdpKJmRlySjwd3AQKF9Kj3XfhWdZapBJqeDp95f3qxoGYNZLKMMsu7+kvcdau1+tqa6R6hvicR5yx+p3PWmHrmDPesncfvdLYtT7Ed+ol7NlYkhT9LF9J5AU/vpVwqbe9iCDo0I6IlrY1RrfN8slNX/Mjz2wqEF066ZGpvNmmR2ZQy4WXar9d2hH03rx/HqeFensX1XeNO1XvyJ5SFD7IGtkM1W4sScjSCzkMZrk4cOpWsmVqZTzPYCeBPcrs6LN5cmMM/J3AUk41gKMUAWOJmVpBJceWgcBt10MdyuPMrefnzv0WC69e1gI3gAwGSqs6mQPr98ljjym+tVKr+p+eoFSl+w9ApJPgtntT8znnwW3QQMTHwVq4SBkLHwfLJCg8XWUiO1SZowJwISr+SYtDv2oxW54AoVM/UobKDz8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
