travis:
  secure:
    BINSTAR_TOKEN: HVQfOAbFWnHLPsBQdKL6Yyqf1g93idd+MZTUTGzTigOvODuy2ZpenLGm7XY3GxWTwoVtzaeSv9caSXwrBFoAANOOQ/JKEO4TZgcZN1eP5GfoORoi15ARckQdLv1YtxAOGJ9SU+kMOs56Lq6FM5+k2aX5Ebd3HJIZF8G5DfXdWTC5aYPMo4d6n93PjFOkFXYUVmLKzeOx7IZ14iZpgKWvJspQDaEx5EFZxohEW4uRlKa1uTJcvo2rxy8UNsxYAeSk8phyUYXn74T6gVFPMv0weFIsnQQa2ZENSAytzwpOnaqh8yYVSFFQX74XU5UMYnn/8XYsSxnO4y14cfWR8IIDD3mDlhe4MwdbiJUJGF3IQQBjlyBgCiU4f0G3/zpoDcAw/eanybhcCuLJ/Mt87UQJDIhePR1DjQ7JdgOLgSLZKepPmqN9uRNoUHhp2Nn8VFNlipAz1Ge4G6D4YcCSvtPmBczrQeOX/J/We7DDefcoU2WL/4zc01DsnJsvagyUaEIlvsj4fctOdrjThBlx1lmuA5C7FTLp1f4HEgHPInsIZjNyV8j5WBcGk12YNmKo3uDKkLLvKZPjy5z4zYnOiFbbrKakYC/vTmWB7PzK6G2c+fbVRLtT/heu3XFFWdzDl3BlzbcUyfbYxNmlAY+nX3Fylnr+nB7Nd/IAAhMD9sP2iOI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
