travis:
  secure:
    BINSTAR_TOKEN: rkCwQg+xiwVg9ZCYdPGqwJDOIg4ZY5WYVz+lo1zC9fE0chP2chGHVe0BjwfNDLUmSkglpL9k0+4AHRWcso/Ao8fPd+pAZtLy/HoEDmgonclkrYe8HFywMVaLcLr9hYpLaU4O/qse5H/CYA1fV1qpj4NTNO1aJZDyO/VNkQQKGMkUQoydcjWcCvFCkLzfJ7h+zTU+rFM531zeEJHolynP7W5sw5ZHg/fSOd93E+9FLFSaCG4gnPFfT/yyAp/TtXvltVKvLCN7qGiPYkBJqaeqg3CqwiEmvcgfurbEObjauseoxLZhffX7zV8XkfzSICzp/4U2eVZbFdN4TU06ildyWwN4Gz/664GakfbY4O/mMZDGFgisU4nx7KD5oUNPUu93pF8b5pRPjXmOk8mQOByMAYeBPUW8i1FFdf+74Vv/p+deAXfnhYrYH9ajVkBrdlxQA7+wER/Gue6VhyVv+00++JUwRtwB41OxqOIUj3/0IbpyX7l7O+qtX55wAwDpAhUeDRluFa3gV+JysK+RzF6J9CDBNePria7rpxpg/pGyci6c5umv4JOuVvO4vgjoPprND3lyiwyUhu1dK9fIBnwFO6dmruv83ttE8aydWm3HU6YvL9NlDyXaH/EBU+bz3sqpenah+6cpJDFfcuHNxBwfuk90eJGxGkRmXLSGFcrRrDo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
