appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Nc/1rFP5KKk7BOG8NW44mS3WjejoHN588jhAZZCjRAOL9wFUixD9zyBumyESpVay4VBZrgbfDaZadyPUqh6aPN1zZ0VEGtC8PnOxz7eV4UsXdwQuXI0yX0ZSIPw+WvBpHybW6SF9UWlPAZLLtE7xccd5BuznTCUjI89tybhql7Mo4Teygdn9rdStVY77eV+Q9Odlsp3E6iIfKC/2kXvqiYcK0ljnVufBdrLYn4B6wjG1qaF/KKlrmtKZ1qx8L/NhEs6P5C4q6ro6t+syOK0RZaUeI17mu24XGQcx0fy02slb+4ECyejdbpj0Z8wVP78p5jbwTv+jCyG4Bi5f9RweyiHyAGn7oCBOaD56ZuNlBU1V3CM34mGmaiHisNFU5ATS4EPnHrEhaIVJekcui3sAI9XEkzY8h8/yC+Hhahk41Zumpa2i6gLHapR9waaTsPSqwIxHXhEOh8ueS2bqEnO0TtyYRO3W9uk9sbgqI0j6ULCR7YysxRvQkfgas4Hfu/OdS6cZAwKCP1LZCnzjf5cfn8/9f5EUOqs4BWQX/H8MXwvyP1J3Y9Un1qWzqKzf/wd0pin5RuEPKm0hKseaqgYnmw+AyLSx+Hqq4WTkeB0UcZVuXcN2EF+Ny8QcJgCfvwY1fK44OYK+fUiWkK3g0YmNpJ8IvtgE/HyIjJCMORFEI9I=}
